### ISSUE TITLE
Missing speaklater dependency

### ISSUE THREAD

**Issue by tdbs** [derkan/flask-locale#1]
It seems there's a dependency missing:

`Collecting Flask-Locale (from -r requirements.txt (line 14))
  Using cached Flask-Locale-1.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8k/dhbd8t8x6_sdp3tvmn05278c0000gn/T/pip-build-37f6z643/Flask-Locale/setup.py", line 8, in <module>
        import flask_locale
      File "/private/var/folders/8k/dhbd8t8x6_sdp3tvmn05278c0000gn/T/pip-build-37f6z643/Flask-Locale/flask_locale/__init__.py", line 17, in <module>
        from speaklater import make_lazy_string
    ModuleNotFoundError: No module named 'speaklater'`

**Comment by derkan** [comment]
Which python version are you using? `speaklater` lib is defined in `requirements.txt`.

**Comment by tdbs** [comment]
I'm using python 3.6.5

My issue still remains the same, i have the same error:

`
File "/Users/tiagosilva/repos/naltio/venv/lib/python3.6/site-packages/flask_locale/__init__.py", line 17, in <module>
    from speaklater3 import make_lazy_string
ModuleNotFoundError: No module named 'speaklater3'
`
