### ISSUE TITLE
No module named 'speaklater3'

### ISSUE THREAD

**Issue by tdbs** [derkan/flask-locale#2]
File "/Users/tiagosilva/repos/naltio/venv/lib/python3.6/site-packages/flask_locale/__init__.py", line 17, in <module>
    from speaklater3 import make_lazy_string
ModuleNotFoundError: No module named 'speaklater3'

This is on version 1.0.3 of flask-locale with python 3.6.5

**Comment by tdbs** [comment]
Your own demo doesn't work.

Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    from flask_locale import Locale, _
  File "/Users/tiagosilva/tests/flask_locale/venv/lib/python3.6/site-packages/flask_locale/__init__.py", line 17, in <module>
    from speaklater3 import make_lazy_string
ModuleNotFoundError: No module named 'speaklater3'

**Comment by derkan** [comment]
Speaklater was not compatible with py3, so I had used speaklater3 fork of it, now orginal speaklater plays [nice with py3](https://github.com/python-babel/flask-babel/pull/38).
